# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options="-Xmx2048m"

# AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Fix for jlink / JdkImageTransform issues on Windows
android.jdk.category.allowlist=com.android.tools.build:gradle:8.7.3

# Other optimizations
android.defaults.buildfeatures.resvalues=true
android.enableAppCompileTimeRClass=false
kotlin.code.style=official
